## Accessing raw data

In [46]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', 500)

In [151]:
df = pd.read_parquet('../data/vehicles_EDA/[Paris] Amsterdam x Clichy.parquet')

df['Hour'] = df['t'].dt.hour
df['Day of the Month'] = df['t'].dt.day
df['Day Name'] =  df['t'].dt.day_name()
df = df.reset_index(drop=True)


df_hour = df.groupby('Hour')[['2_wheelers', '4_wheelers']].mean().reset_index()
df_hour['2_wheelers'] = df_hour['2_wheelers'].astype(int)
df_hour['4_wheelers'] = df_hour['4_wheelers'].astype(int)


df_day = df.groupby('Day of the Month')[['2_wheelers', '4_wheelers']].mean().reset_index()
df_day['2_wheelers'] = df_day['2_wheelers'].astype(int)
df_day['4_wheelers'] = df_day['4_wheelers'].astype(int)


df_day_name = df.groupby('Day Name')[['2_wheelers', '4_wheelers']].mean().reset_index()
df_day_name['2_wheelers'] = df_day_name['2_wheelers'].astype(int)
df_day_name['4_wheelers'] = df_day_name['4_wheelers'].astype(int)

In [152]:
df_day_name

    Day Name  2_wheelers  4_wheelers
0     Friday         188          99
1     Monday         181          86
2   Saturday         146          97
3     Sunday         112          79
4   Thursday         205          95
5    Tuesday         204          94
6  Wednesday         201          93

In [155]:
cats = [ 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
df_day_name.groupby(['Day Name']).sum().reindex(cats).reset_index()

    Day Name  2_wheelers  4_wheelers
0     Monday         181          86
1    Tuesday         204          94
2  Wednesday         201          93
3   Thursday         205          95
4     Friday         188          99
5   Saturday         146          97
6     Sunday         112          79

In [135]:
import plotly.express as px
fig = px.line(df_day_name, x="Day Name", y=['2_wheelers', '4_wheelers'], labels={'variable' : 'type of vehicle', 'value' : 'Vehicles',
                                                                         'hour' : 'Hour'},
#              hover_data={"date": "|%B %d, %Y"},
              title='Average Traffic by day of month', markers=True)
fig.update_layout(
    xaxis = dict(
        tickmode = 'linear',
        tick0 = 0.0,
        dtick = 1.0
    )
)
fig.update_traces(marker_size=10)
fig.show()

In [138]:
import glob    
dir_path = '../data/vehicles_EDA/*.parquet'
file_names = sorted(glob.glob(dir_path))

In [144]:
file_names[0].split('/')[-1].split('.')[0]

'[Paris] Amsterdam x Clichy'

In [145]:
junction_labels[0]

NameError: name 'junction_labels' is not defined

In [146]:
junction_labels = ['[Paris] Rivoli x Nicolas Flamel',
                    '[Paris] Amsterdam x Clichy',
                    '[Paris] Quai de Valmy',
                    '[Paris] Quai de Jemmapes',
                    '[Paris] CF892 Rivoli x Bourdonnais',
                    '[Paris] CF318 Rivoli x Lobau',
                    '[Paris] CF1 Rivoli x Sébastopol',
#                    '[Paris] CF4 Poissonnière x Montmartre EST',
                    '[Paris] CF4 Poissonnière x Montmartre OUEST']

In [147]:
junction_labels[0]

'[Paris] Rivoli x Nicolas Flamel'

In [150]:
import os
os.path.join( 'data', 'vehicles_EDA', junction_labels[0] + '.parquet' )

'data/vehicles_EDA/[Paris] Rivoli x Nicolas Flamel.parquet'

In [ ]:
data/vehicles_EDA/[Paris] Rivoli x Nicolas Flamel.parquet

In [156]:
import glob    
dir_path = '../data/vehicles_EDA/*.parquet'
file_names = sorted(glob.glob(dir_path))

In [175]:
file_names[0].split('.')[-2]

'/data/vehicles_EDA/[Paris] Amsterdam x Clichy'

In [176]:
file_names[0].split('.')[-2]  + '.pkl'

'/data/vehicles_EDA/[Paris] Amsterdam x Clichy.pkl'

In [165]:
    df = []
    for file in file_names:
        df.append(pd.read_parquet(file))
        print(file)
    df = pd.concat(df)

../data/vehicles_EDA/[Paris] Amsterdam x Clichy.parquet
../data/vehicles_EDA/[Paris] CF1 Rivoli x Sébastopol.parquet
../data/vehicles_EDA/[Paris] CF318 Rivoli x Lobau.parquet
../data/vehicles_EDA/[Paris] CF4 Poissonnière x Montmartre EST.parquet
../data/vehicles_EDA/[Paris] CF4 Poissonnière x Montmartre OUEST.parquet
../data/vehicles_EDA/[Paris] CF892 Rivoli x Bourdonnais.parquet
../data/vehicles_EDA/[Paris] Quai de Jemmapes.parquet
../data/vehicles_EDA/[Paris] Quai de Valmy.parquet
../data/vehicles_EDA/[Paris] Rivoli x Nicolas Flamel.parquet

In [166]:
df.shape

(177461, 6)

In [167]:
df

,label,latitude,longitude,t,2_wheelers,4_wheelers
0,[Paris] Amsterdam x Clichy,48.883513,2.327263,2020-07-06 15:00:00+00:00,65.0,24.0
1,[Paris] Amsterdam x Clichy,48.883513,2.327263,2020-07-06 16:00:00+00:00,456.0,166.0
2,[Paris] Amsterdam x Clichy,48.883513,2.327263,2020-07-06 17:00:00+00:00,409.0,145.0
3,[Paris] Amsterdam x Clichy,48.883513,2.327263,2020-07-06 18:00:00+00:00,291.0,144.0
4,[Paris] Amsterdam x Clichy,48.883513,2.327263,2020-07-06 19:00:00+00:00,169.0,115.0
...,...,...,...,...,...,...
25083,[Paris] Rivoli x Nicolas Flamel,48.858273,2.349109,2023-05-21 17:00:00+00:00,969.0,258.0
25084,[Paris] Rivoli x Nicolas Flamel,48.858273,2.349109,2023-05-21 18:00:00+00:00,719.0,213.0
25085,[Paris] Rivoli x Nicolas Flamel,48.858273,2.349109,2023-05-21 19:00:00+00:00,475.0,197.0
25086,[Paris] Rivoli x Nicolas Flamel,48.858273,2.349109,2023-05-21 20:00:00+00:00,399.0,191.0
25087,[Paris] Rivoli x Nicolas Flamel,48.858273,2.349109,2023-05-21 21:00:00+00:00,277.0,160.0

In [164]:
df['label']

Timestamp('2023-05-21 21:00:00+0000', tz='UTC')

In [ ]:
            df["Hour"] = df["t"].dt.hour
            df["Day of the Month"] = df["t"].dt.day
            df["Day Name"] = df["t"].dt.day_name()
            df['Total'] = df['2_wheelers'] + df['4_wheelers']
            df = df.reset_index(drop=True)
            df_hour = df.groupby("Hour")[["2_wheelers", "4_wheelers", 'Total']].mean().reset_index()
            df_hour["2_wheelers"] = df_hour["2_wheelers"].astype(int)
            df_hour["4_wheelers"] = df_hour["4_wheelers"].astype(int)
            df_hour["Total"] = df_hour["Total"].astype(int)


            df_day = (
                df.groupby("Day of the Month")[["2_wheelers", "4_wheelers", "Total"]].mean().reset_index()
            )
            df_day["2_wheelers"] = df_day["2_wheelers"].astype(int)
            df_day["4_wheelers"] = df_day["4_wheelers"].astype(int)
            df_day["Total"] = df_day["Total"].astype(int)

            df_day_name = df.groupby("Day Name")[["2_wheelers", "4_wheelers","Total"]].mean().reset_index()
            df_day_name["2_wheelers"] = df_day_name["2_wheelers"].astype(int)
            df_day_name["4_wheelers"] = df_day_name["4_wheelers"].astype(int)
            df_day_name["Total"] = df_day_name["Total"].astype(int)
            cats = [ 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
            df_day_name = df_day_name.groupby(['Day Name']).sum().reindex(cats).reset_index()

In [169]:
import pickle

In [170]:
pickled_model = pickle.load(open('../data/vehicles_EDA/model.pkl', 'rb'))

In [172]:
pickled_model[0]

    Hour  2_wheelers  4_wheelers  Total
0      0         105         122    228
1      1          65          91    157
2      2          41          68    110
3      3          41          69    110
4      4          70         103    173
5      5         178         159    338
6      6         535         196    731
7      7         787         219   1006
8      8         637         241    878
9      9         542         248    790
10    10         653         245    899
11    11         717         238    955
12    12         747         240    988
13    13         798         250   1049
14    14         879         253   1133
15    15        1008         253   1261
16    16        1206         252   1459
17    17        1191         248   1439
18    18         878         236   1114
19    19         548         220    768
20    20         402         201    604
21    21         344         192    536
22    22         249         191    440
23    23         157         163    320

In [177]:
file_names[0].split('.')[-2] +'/save/' + '.pkl'

'/data/vehicles_EDA/[Paris] Amsterdam x Clichy/save/.pkl'

In [178]:
file_names[0].split('.')[-2] + '.pkl'

'/data/vehicles_EDA/[Paris] Amsterdam x Clichy.pkl'

In [198]:
dir_path = '../data/vehicles_EDA/*.pkl'
file_names = sorted(glob.glob(dir_path))

file = file_names[0]


df_hour_junc = []
for file in file_names:
        df = pickle.load(open(file, 'rb'))


        df_hour_junc.append(   df[0].add_suffix(  '_' + file.split('/')[-1].split('.')[0])   )


dfd =  pd.concat(df_hour_junc,axis=1)

In [199]:
dfd

,Hour_[Paris] Amsterdam x Clichy,2_wheelers_[Paris] Amsterdam x Clichy,4_wheelers_[Paris] Amsterdam x Clichy,Total_[Paris] Amsterdam x Clichy,Hour_[Paris] CF1 Rivoli x Sébastopol,2_wheelers_[Paris] CF1 Rivoli x Sébastopol,4_wheelers_[Paris] CF1 Rivoli x Sébastopol,Total_[Paris] CF1 Rivoli x Sébastopol,Hour_[Paris] CF318 Rivoli x Lobau,2_wheelers_[Paris] CF318 Rivoli x Lobau,4_wheelers_[Paris] CF318 Rivoli x Lobau,Total_[Paris] CF318 Rivoli x Lobau,Hour_[Paris] CF4 Poissonnière x Montmartre EST,2_wheelers_[Paris] CF4 Poissonnière x Montmartre EST,4_wheelers_[Paris] CF4 Poissonnière x Montmartre EST,Total_[Paris] CF4 Poissonnière x Montmartre EST,Hour_[Paris] CF4 Poissonnière x Montmartre OUEST,2_wheelers_[Paris] CF4 Poissonnière x Montmartre OUEST,4_wheelers_[Paris] CF4 Poissonnière x Montmartre OUEST,Total_[Paris] CF4 Poissonnière x Montmartre OUEST,Hour_[Paris] CF892 Rivoli x Bourdonnais,2_wheelers_[Paris] CF892 Rivoli x Bourdonnais,4_wheelers_[Paris] CF892 Rivoli x Bourdonnais,Total_[Paris] CF892 Rivoli x Bourdonnais,Hour_[Paris] Quai de Jemmapes,2_wheelers_[Paris] Quai de Jemmapes,4_wheelers_[Paris] Quai de Jemmapes,Total_[Paris] Quai de Jemmapes,Hour_[Paris] Quai de Valmy,2_wheelers_[Paris] Quai de Valmy,4_wheelers_[Paris] Quai de Valmy,Total_[Paris] Quai de Valmy,Hour_[Paris] Rivoli x Nicolas Flamel,2_wheelers_[Paris] Rivoli x Nicolas Flamel,4_wheelers_[Paris] Rivoli x Nicolas Flamel,Total_[Paris] Rivoli x Nicolas Flamel
0,0,33,59,92,0,220,602,822,0,99,88,188,0,35,84,119,0,81,479,561,0,102,116,219,0,40,18,58,0,36,2,38,0,105,122,228
1,1,22,41,64,1,138,456,595,1,63,62,126,1,22,67,90,1,56,383,440,1,67,83,150,1,26,13,39,1,24,1,26,1,65,91,157
2,2,16,33,50,2,88,361,450,2,40,48,89,2,15,48,64,2,34,267,302,2,42,65,107,2,15,9,25,2,16,1,17,2,41,68,110
3,3,23,39,63,3,87,365,453,3,39,55,95,3,13,38,51,3,38,259,298,3,44,74,118,3,12,9,22,3,18,1,20,3,41,69,110
4,4,43,54,97,4,124,527,652,4,61,86,148,4,12,40,53,4,64,345,409,4,71,115,187,4,17,17,34,4,36,3,39,4,70,103,173
5,5,100,68,168,5,276,674,950,5,148,136,284,5,21,55,76,5,131,483,615,5,180,183,363,5,43,27,71,5,101,5,107,5,178,159,338
6,6,277,86,363,6,747,724,1472,6,457,171,629,6,66,75,142,6,362,584,946,6,576,232,809,6,131,38,169,6,321,7,328,6,535,196,731
7,7,380,106,486,7,1087,772,1859,7,709,195,905,7,123,94,218,7,583,624,1208,7,897,268,1166,7,192,54,246,7,534,8,543,7,787,219,1006
8,8,267,121,388,8,887,819,1706,8,591,212,804,8,127,119,246,8,494,663,1157,8,730,300,1031,8,149,65,215,8,448,8,457,8,637,241,878
9,9,195,129,324,9,715,849,1564,9,498,218,716,9,135,136,272,9,382,710,1092,9,560,306,866,9,119,75,194,9,299,9,308,9,542,248,790
10,10,223,127,350,10,834,857,1692,10,601,218,819,10,187,140,328,10,442,744,1186,10,650,306,956,10,141,78,220,10,315,9,324,10,653,245,899
11,11,229,123,352,11,919,866,1786,11,666,210,877,11,217,143,361,11,483,757,1240,11,709,301,1010,11,173,74,248,11,333,8,342,11,717,238,955
12,12,212,122,335,12,949,875,1825,12,694,208,903,12,220,144,364,12,466,762,1228,12,742,285,1028,12,183,73,257,12,315,8,324,12,747,240,988
13,13,210,123,333,13,1006,854,1860,13,737,221,958,13,217,148,366,13,444,780,1224,13,812,285,1098,13,198,81,280,13,315,8,323,13,798,250,1049
14,14,220,119,339,14,1077,824,1901,14,806,226,1033,14,211,149,360,14,428,781,1210,14,912,286,1198,14,227,87,315,14,346,7,354,14,879,253,1133
15,15,264,114,378,15,1249,815,2064,15,915,221,1136,15,247,145,393,15,463,789,1253,15,1043,292,1335,15,287,88,375,15,419,7,426,15,1008,253,1261
16,16,341,110,451,16,1578,831,2410,16,1084,216,1300,16,326,139,465,16,561,793,1355,16,1245,277,1522,16,373,81,454,16,533,7,541,16,1206,252,1459
17,17,361,109,470,17,1705,850,2555,17,1071,205,1276,17,347,140,487,17,589,782,1371,17,1223,271,1494,17,392,69,461,17,532,7,539,17,1191,248,1439
18,18,289,104,394,18,1359,863,2222,18,808,185,994,18,278,131,409,18,487,725,1213,18,889,253,1143,18,306,58,364,18,397,6,403,18,878,236,1114
19,19,190,92,282,19,924,848,1772,19,517,168,685,19,182,112,294,19,334,673,1008,19,532,232,764,19,198,48,246,19,242,4,246,19,548,220,768
20,20,131,84,215,20,763,854,1618,20,374,154,529,20,131,98,229,20,245,644,889,20,376,213,589,20,147,43,190,20,156,4,160,20,402,201,604
21,21,99,86,186,21,712,869,1582,21,317,146,464,21,106,100,207,21,210,647,857,21,332,202,534,21,132,38,171,21,123,3,126,21,344,192,536
22,22,72,81,153,22,534,849,1383,22,234,143,377,22,76,102,178,22,165,622,788,22,243,191,434,22,99,33,132,22,89,2,92,22,249,191,440
23,23,46,72,119,23,334,743,1078,23,148,122,270,23,48,96,145,23,110,558,668,23,152,159,312,23,61,25,86,23,55,2,58,23,157,163,320

In [195]:
file_names

['../data/vehicles_EDA/[Paris] Amsterdam x Clichy.pkl',
 '../data/vehicles_EDA/[Paris] CF1 Rivoli x Sébastopol.pkl',
 '../data/vehicles_EDA/[Paris] CF318 Rivoli x Lobau.pkl',
 '../data/vehicles_EDA/[Paris] CF4 Poissonnière x Montmartre EST.pkl',
 '../data/vehicles_EDA/[Paris] CF4 Poissonnière x Montmartre OUEST.pkl',
 '../data/vehicles_EDA/[Paris] CF892 Rivoli x Bourdonnais.pkl',
 '../data/vehicles_EDA/[Paris] Quai de Jemmapes.pkl',
 '../data/vehicles_EDA/[Paris] Quai de Valmy.pkl',
 '../data/vehicles_EDA/[Paris] Rivoli x Nicolas Flamel.pkl']

In [196]:
pd.set_option('display.max_columns', 500)

In [204]:
to_plot_names = list(dfd.filter(regex='^2_wheelers').columns)

In [203]:
import plotly.express as px
df = px.data.stocks()
fig = px.line(dfd, x="Hour_[Paris] Amsterdam x Clichy", y=list(dfd.filter(regex='^2_wheelers').columns),
#              hover_data={"date": "|%B %d, %Y"},
              title='custom tick labels')
#fig.update_xaxes(
#    dtick="M1",
#    tickformat="%b\n%Y")
fig.show()

In [206]:
sorted(junction_labels)

['[Paris] Amsterdam x Clichy',
 '[Paris] CF1 Rivoli x Sébastopol',
 '[Paris] CF318 Rivoli x Lobau',
 '[Paris] CF4 Poissonnière x Montmartre OUEST',
 '[Paris] CF892 Rivoli x Bourdonnais',
 '[Paris] Quai de Jemmapes',
 '[Paris] Quai de Valmy',
 '[Paris] Rivoli x Nicolas Flamel']

In [8]:
dir_path = '../data/vehicles_EDA/*.pkl'
file_names = sorted(glob.glob(dir_path))

#file = file_names[0]
df_hour_junc = []
df_day_junc = []
df_dayname_junc = []

for file in file_names:
        df = pickle.load(open(file, 'rb'))
        df_hour_junc.append(   df[0].add_suffix(  '_' + file.split('/')[-1].split('.')[0])   )
        df_day_junc.append(   df[1].add_suffix(  '_' + file.split('/')[-1].split('.')[0])   )
        df_dayname_junc.append(   df[2].add_suffix(  '_' + file.split('/')[-1].split('.')[0])   )

In [2]:
import glob

In [4]:
df_hour_junc

[]

In [7]:
import pickle

In [19]:
df_day_junc[1]

,Day of the Month_[Paris] CF1 Rivoli x Sébastopol,2_wheelers_[Paris] CF1 Rivoli x Sébastopol,4_wheelers_[Paris] CF1 Rivoli x Sébastopol,Total_[Paris] CF1 Rivoli x Sébastopol
0,1,757,742,1500
1,2,768,738,1506
2,3,740,746,1486
3,4,733,763,1496
4,5,730,771,1501
5,6,765,756,1522
6,7,794,741,1536
7,8,786,743,1529
8,9,801,750,1551
9,10,787,750,1537
10,11,794,763,1558
11,12,777,751,1529
12,13,742,745,1487
13,14,727,737,1465
14,15,778,740,1518
15,16,791,758,1549
16,17,782,742,1525
17,18,801,748,1550
18,19,768,733,1501
19,20,754,740,1494
20,21,830,740,1570
21,22,791,753,1544
22,23,760,744,1505
23,24,781,740,1522
24,25,722,745,1467
25,26,648,743,1392
26,27,718,758,1476
27,28,790,746,1536
28,29,743,761,1504
29,30,745,752,1497
30,31,731,740,1472

In [21]:
dir_path = '../data/vehicles_EDA/*.pkl'
file_names = sorted(glob.glob(dir_path))

#file = file_names[0]
df_hour_junc = []
df_day_junc = []
df_dayname_junc = []

for file in file_names:
        df = pickle.load(open(file, 'rb'))
        df_hour_junc.append(   df[0].add_suffix(  '_' + file.split('/')[-1].split('.')[0])   )
        df_day_junc.append(   df[1].add_suffix(  '_' + file.split('/')[-1].split('.')[0])   )
        df_dayname_junc.append(   df[2].add_suffix(  '_' + file.split('/')[-1].split('.')[0])   )


df_hour_junc =  pd.concat(df_hour_junc,axis=1)
df_day_junc =  pd.concat(df_day_junc,axis=1)
df_dayname_junc =  pd.concat(df_dayname_junc,axis=1)

In [22]:
df_hour_junc

,Hour_[Paris] Amsterdam x Clichy,2_wheelers_[Paris] Amsterdam x Clichy,4_wheelers_[Paris] Amsterdam x Clichy,Total_[Paris] Amsterdam x Clichy,Hour_[Paris] CF1 Rivoli x Sébastopol,2_wheelers_[Paris] CF1 Rivoli x Sébastopol,4_wheelers_[Paris] CF1 Rivoli x Sébastopol,Total_[Paris] CF1 Rivoli x Sébastopol,Hour_[Paris] CF318 Rivoli x Lobau,2_wheelers_[Paris] CF318 Rivoli x Lobau,...,4_wheelers_[Paris] Quai de Jemmapes,Total_[Paris] Quai de Jemmapes,Hour_[Paris] Quai de Valmy,2_wheelers_[Paris] Quai de Valmy,4_wheelers_[Paris] Quai de Valmy,Total_[Paris] Quai de Valmy,Hour_[Paris] Rivoli x Nicolas Flamel,2_wheelers_[Paris] Rivoli x Nicolas Flamel,4_wheelers_[Paris] Rivoli x Nicolas Flamel,Total_[Paris] Rivoli x Nicolas Flamel
0,0,33,59,92,0,220,602,822,0,99,...,18,58,0,36,2,38,0,105,122,228
1,1,22,41,64,1,138,456,595,1,63,...,13,39,1,24,1,26,1,65,91,157
2,2,16,33,50,2,88,361,450,2,40,...,9,25,2,16,1,17,2,41,68,110
3,3,23,39,63,3,87,365,453,3,39,...,9,22,3,18,1,20,3,41,69,110
4,4,43,54,97,4,124,527,652,4,61,...,17,34,4,36,3,39,4,70,103,173
5,5,100,68,168,5,276,674,950,5,148,...,27,71,5,101,5,107,5,178,159,338
6,6,277,86,363,6,747,724,1472,6,457,...,38,169,6,321,7,328,6,535,196,731
7,7,380,106,486,7,1087,772,1859,7,709,...,54,246,7,534,8,543,7,787,219,1006
8,8,267,121,388,8,887,819,1706,8,591,...,65,215,8,448,8,457,8,637,241,878
9,9,195,129,324,9,715,849,1564,9,498,...,75,194,9,299,9,308,9,542,248,790
10,10,223,127,350,10,834,857,1692,10,601,...,78,220,10,315,9,324,10,653,245,899
11,11,229,123,352,11,919,866,1786,11,666,...,74,248,11,333,8,342,11,717,238,955
12,12,212,122,335,12,949,875,1825,12,694,...,73,257,12,315,8,324,12,747,240,988
13,13,210,123,333,13,1006,854,1860,13,737,...,81,280,13,315,8,323,13,798,250,1049
14,14,220,119,339,14,1077,824,1901,14,806,...,87,315,14,346,7,354,14,879,253,1133
15,15,264,114,378,15,1249,815,2064,15,915,...,88,375,15,419,7,426,15,1008,253,1261
16,16,341,110,451,16,1578,831,2410,16,1084,...,81,454,16,533,7,541,16,1206,252,1459
17,17,361,109,470,17,1705,850,2555,17,1071,...,69,461,17,532,7,539,17,1191,248,1439
18,18,289,104,394,18,1359,863,2222,18,808,...,58,364,18,397,6,403,18,878,236,1114
19,19,190,92,282,19,924,848,1772,19,517,...,48,246,19,242,4,246,19,548,220,768
20,20,131,84,215,20,763,854,1618,20,374,...,43,190,20,156,4,160,20,402,201,604
21,21,99,86,186,21,712,869,1582,21,317,...,38,171,21,123,3,126,21,344,192,536
22,22,72,81,153,22,534,849,1383,22,234,...,33,132,22,89,2,92,22,249,191,440
23,23,46,72,119,23,334,743,1078,23,148,...,25,86,23,55,2,58,23,157,163,320

In [23]:
df_hour_junc.columns

Index(['Hour_[Paris] Amsterdam x Clichy',
       '2_wheelers_[Paris] Amsterdam x Clichy',
       '4_wheelers_[Paris] Amsterdam x Clichy',
       'Total_[Paris] Amsterdam x Clichy',
       'Hour_[Paris] CF1 Rivoli x Sébastopol',
       '2_wheelers_[Paris] CF1 Rivoli x Sébastopol',
       '4_wheelers_[Paris] CF1 Rivoli x Sébastopol',
       'Total_[Paris] CF1 Rivoli x Sébastopol',
       'Hour_[Paris] CF318 Rivoli x Lobau',
       '2_wheelers_[Paris] CF318 Rivoli x Lobau',
       '4_wheelers_[Paris] CF318 Rivoli x Lobau',
       'Total_[Paris] CF318 Rivoli x Lobau',
       'Hour_[Paris] CF4 Poissonnière x Montmartre OUEST',
       '2_wheelers_[Paris] CF4 Poissonnière x Montmartre OUEST',
       '4_wheelers_[Paris] CF4 Poissonnière x Montmartre OUEST',
       'Total_[Paris] CF4 Poissonnière x Montmartre OUEST',
       'Hour_[Paris] CF892 Rivoli x Bourdonnais',
       '2_wheelers_[Paris] CF892 Rivoli x Bourdonnais',
       '4_wheelers_[Paris] CF892 Rivoli x Bourdonnais',
       'Total_[Paris] CF892 Rivoli x Bourdonnais',
       'Hour_[Paris] Quai de Jemmapes', '2_wheelers_[Paris] Quai de Jemmapes',
       '4_wheelers_[Paris] Quai de Jemmapes', 'Total_[Paris] Quai de Jemmapes',
       'Hour_[Paris] Quai de Valmy', '2_wheelers_[Paris] Quai de Valmy',
       '4_wheelers_[Paris] Quai de Valmy', 'Total_[Paris] Quai de Valmy',
       'Hour_[Paris] Rivoli x Nicolas Flamel',
       '2_wheelers_[Paris] Rivoli x Nicolas Flamel',
       '4_wheelers_[Paris] Rivoli x Nicolas Flamel',
       'Total_[Paris] Rivoli x Nicolas Flamel'],
      dtype='object')

In [24]:
df_hour_junc.rename(columns = lambda x: x.removeprefix('prefix_i_want_to_remove'))

,Hour_[Paris] Amsterdam x Clichy,2_wheelers_[Paris] Amsterdam x Clichy,4_wheelers_[Paris] Amsterdam x Clichy,Total_[Paris] Amsterdam x Clichy,Hour_[Paris] CF1 Rivoli x Sébastopol,2_wheelers_[Paris] CF1 Rivoli x Sébastopol,4_wheelers_[Paris] CF1 Rivoli x Sébastopol,Total_[Paris] CF1 Rivoli x Sébastopol,Hour_[Paris] CF318 Rivoli x Lobau,2_wheelers_[Paris] CF318 Rivoli x Lobau,...,4_wheelers_[Paris] Quai de Jemmapes,Total_[Paris] Quai de Jemmapes,Hour_[Paris] Quai de Valmy,2_wheelers_[Paris] Quai de Valmy,4_wheelers_[Paris] Quai de Valmy,Total_[Paris] Quai de Valmy,Hour_[Paris] Rivoli x Nicolas Flamel,2_wheelers_[Paris] Rivoli x Nicolas Flamel,4_wheelers_[Paris] Rivoli x Nicolas Flamel,Total_[Paris] Rivoli x Nicolas Flamel
0,0,33,59,92,0,220,602,822,0,99,...,18,58,0,36,2,38,0,105,122,228
1,1,22,41,64,1,138,456,595,1,63,...,13,39,1,24,1,26,1,65,91,157
2,2,16,33,50,2,88,361,450,2,40,...,9,25,2,16,1,17,2,41,68,110
3,3,23,39,63,3,87,365,453,3,39,...,9,22,3,18,1,20,3,41,69,110
4,4,43,54,97,4,124,527,652,4,61,...,17,34,4,36,3,39,4,70,103,173
5,5,100,68,168,5,276,674,950,5,148,...,27,71,5,101,5,107,5,178,159,338
6,6,277,86,363,6,747,724,1472,6,457,...,38,169,6,321,7,328,6,535,196,731
7,7,380,106,486,7,1087,772,1859,7,709,...,54,246,7,534,8,543,7,787,219,1006
8,8,267,121,388,8,887,819,1706,8,591,...,65,215,8,448,8,457,8,637,241,878
9,9,195,129,324,9,715,849,1564,9,498,...,75,194,9,299,9,308,9,542,248,790
10,10,223,127,350,10,834,857,1692,10,601,...,78,220,10,315,9,324,10,653,245,899
11,11,229,123,352,11,919,866,1786,11,666,...,74,248,11,333,8,342,11,717,238,955
12,12,212,122,335,12,949,875,1825,12,694,...,73,257,12,315,8,324,12,747,240,988
13,13,210,123,333,13,1006,854,1860,13,737,...,81,280,13,315,8,323,13,798,250,1049
14,14,220,119,339,14,1077,824,1901,14,806,...,87,315,14,346,7,354,14,879,253,1133
15,15,264,114,378,15,1249,815,2064,15,915,...,88,375,15,419,7,426,15,1008,253,1261
16,16,341,110,451,16,1578,831,2410,16,1084,...,81,454,16,533,7,541,16,1206,252,1459
17,17,361,109,470,17,1705,850,2555,17,1071,...,69,461,17,532,7,539,17,1191,248,1439
18,18,289,104,394,18,1359,863,2222,18,808,...,58,364,18,397,6,403,18,878,236,1114
19,19,190,92,282,19,924,848,1772,19,517,...,48,246,19,242,4,246,19,548,220,768
20,20,131,84,215,20,763,854,1618,20,374,...,43,190,20,156,4,160,20,402,201,604
21,21,99,86,186,21,712,869,1582,21,317,...,38,171,21,123,3,126,21,344,192,536
22,22,72,81,153,22,534,849,1383,22,234,...,33,132,22,89,2,92,22,249,191,440
23,23,46,72,119,23,334,743,1078,23,148,...,25,86,23,55,2,58,23,157,163,320

In [33]:
columns_to_plot =   ['Hour_[Paris] Amsterdam x Clichy'] +  list(df_hour_junc.filter(regex='^{}'.format('2_wheelers')).columns)

In [34]:
columns_to_plot

['Hour_[Paris] Amsterdam x Clichy',
 '2_wheelers_[Paris] Amsterdam x Clichy',
 '2_wheelers_[Paris] CF1 Rivoli x Sébastopol',
 '2_wheelers_[Paris] CF318 Rivoli x Lobau',
 '2_wheelers_[Paris] CF4 Poissonnière x Montmartre OUEST',
 '2_wheelers_[Paris] CF892 Rivoli x Bourdonnais',
 '2_wheelers_[Paris] Quai de Jemmapes',
 '2_wheelers_[Paris] Quai de Valmy',
 '2_wheelers_[Paris] Rivoli x Nicolas Flamel']

In [35]:
dff = df_hour_junc[columns_to_plot]

In [36]:
dff

,Hour_[Paris] Amsterdam x Clichy,2_wheelers_[Paris] Amsterdam x Clichy,2_wheelers_[Paris] CF1 Rivoli x Sébastopol,2_wheelers_[Paris] CF318 Rivoli x Lobau,2_wheelers_[Paris] CF4 Poissonnière x Montmartre OUEST,2_wheelers_[Paris] CF892 Rivoli x Bourdonnais,2_wheelers_[Paris] Quai de Jemmapes,2_wheelers_[Paris] Quai de Valmy,2_wheelers_[Paris] Rivoli x Nicolas Flamel
0,0,33,220,99,81,102,40,36,105
1,1,22,138,63,56,67,26,24,65
2,2,16,88,40,34,42,15,16,41
3,3,23,87,39,38,44,12,18,41
4,4,43,124,61,64,71,17,36,70
5,5,100,276,148,131,180,43,101,178
6,6,277,747,457,362,576,131,321,535
7,7,380,1087,709,583,897,192,534,787
8,8,267,887,591,494,730,149,448,637
9,9,195,715,498,382,560,119,299,542
10,10,223,834,601,442,650,141,315,653
11,11,229,919,666,483,709,173,333,717
12,12,212,949,694,466,742,183,315,747
13,13,210,1006,737,444,812,198,315,798
14,14,220,1077,806,428,912,227,346,879
15,15,264,1249,915,463,1043,287,419,1008
16,16,341,1578,1084,561,1245,373,533,1206
17,17,361,1705,1071,589,1223,392,532,1191
18,18,289,1359,808,487,889,306,397,878
19,19,190,924,517,334,532,198,242,548
20,20,131,763,374,245,376,147,156,402
21,21,99,712,317,210,332,132,123,344
22,22,72,534,234,165,243,99,89,249
23,23,46,334,148,110,152,61,55,157

In [37]:
dff.columns.map(lambda x: x.removeprefix('2_wheelers_'))

Index(['Hour_[Paris] Amsterdam x Clichy', '[Paris] Amsterdam x Clichy',
       '[Paris] CF1 Rivoli x Sébastopol', '[Paris] CF318 Rivoli x Lobau',
       '[Paris] CF4 Poissonnière x Montmartre OUEST',
       '[Paris] CF892 Rivoli x Bourdonnais', '[Paris] Quai de Jemmapes',
       '[Paris] Quai de Valmy', '[Paris] Rivoli x Nicolas Flamel'],
      dtype='object')

In [38]:
dir_path = '../data/vehicles_EDA/*.pkl'
file_names = sorted(glob.glob(dir_path))

#file = file_names[0]
df_hour_junc = []
df_day_junc = []
df_dayname_junc = []

for file in file_names:
        df = pickle.load(open(file, 'rb'))
        df_hour_junc.append(   df[0].add_suffix(  '_' + file.split('/')[-1].split('.')[0])   )
        df_day_junc.append(   df[1].add_suffix(  '_' + file.split('/')[-1].split('.')[0])   )
        df_dayname_junc.append(   df[2].add_suffix(  '_' + file.split('/')[-1].split('.')[0])   )


df_hour_junc =  pd.concat(df_hour_junc,axis=1)
df_day_junc =  pd.concat(df_day_junc,axis=1)
df_dayname_junc =  pd.concat(df_dayname_junc,axis=1)

In [39]:
df_types = [df_hour_junc, df_day_junc, df_dayname_junc]
title_names = ['Average Traffic by hour', 'Average Traffic by day of month', 'Average Traffic by day name']

In [40]:
option_2 = '2_wheelers'

In [41]:
type = "Hour_[Paris] Amsterdam x Clichy"

In [42]:
i=0

In [43]:
columns_to_plot =[type] + list(df_types[i].filter(regex='^{}'.format(option_2)).columns)
df_to_plot = df_types[i][columns_to_plot]
df_to_plot.columns = df_to_plot.columns.map(lambda x: x.removeprefix(option_2 + '_'))

In [52]:
df_to_plot

,Hour_[Paris] Amsterdam x Clichy,[Paris] Amsterdam x Clichy,[Paris] CF1 Rivoli x Sébastopol,[Paris] CF318 Rivoli x Lobau,[Paris] CF4 Poissonnière x Montmartre OUEST,[Paris] CF892 Rivoli x Bourdonnais,[Paris] Quai de Jemmapes,[Paris] Quai de Valmy,[Paris] Rivoli x Nicolas Flamel
0,0,33,220,99,81,102,40,36,105
1,1,22,138,63,56,67,26,24,65
2,2,16,88,40,34,42,15,16,41
3,3,23,87,39,38,44,12,18,41
4,4,43,124,61,64,71,17,36,70
5,5,100,276,148,131,180,43,101,178
6,6,277,747,457,362,576,131,321,535
7,7,380,1087,709,583,897,192,534,787
8,8,267,887,591,494,730,149,448,637
9,9,195,715,498,382,560,119,299,542
10,10,223,834,601,442,650,141,315,653
11,11,229,919,666,483,709,173,333,717
12,12,212,949,694,466,742,183,315,747
13,13,210,1006,737,444,812,198,315,798
14,14,220,1077,806,428,912,227,346,879
15,15,264,1249,915,463,1043,287,419,1008
16,16,341,1578,1084,561,1245,373,533,1206
17,17,361,1705,1071,589,1223,392,532,1191
18,18,289,1359,808,487,889,306,397,878
19,19,190,924,517,334,532,198,242,548
20,20,131,763,374,245,376,147,156,402
21,21,99,712,317,210,332,132,123,344
22,22,72,534,234,165,243,99,89,249
23,23,46,334,148,110,152,61,55,157

In [49]:
import plotly.express as px

In [50]:
fig = px.line(
                                df_to_plot,
                                x='Hour_[Paris] Amsterdam x Clichy',
                                y=columns_to_plot[1:],
                                labels={"variable": "Junction", "value": "Vehicles"},
                                #              hover_data={"date": "|%B %d, %Y"},
                                title=title_names[i],
                                markers=True,
                            )

ValueError: All arguments should have the same length. The length of argument `y` is 8, whereas the length of  previously-processed arguments ['Hour_[Paris] Amsterdam x Clichy'] is 24

In [53]:
columns_to_plot[1:]

['2_wheelers_[Paris] Amsterdam x Clichy',
 '2_wheelers_[Paris] CF1 Rivoli x Sébastopol',
 '2_wheelers_[Paris] CF318 Rivoli x Lobau',
 '2_wheelers_[Paris] CF4 Poissonnière x Montmartre OUEST',
 '2_wheelers_[Paris] CF892 Rivoli x Bourdonnais',
 '2_wheelers_[Paris] Quai de Jemmapes',
 '2_wheelers_[Paris] Quai de Valmy',
 '2_wheelers_[Paris] Rivoli x Nicolas Flamel']

In [55]:
df_to_plot.columns[1:]

Index(['[Paris] Amsterdam x Clichy', '[Paris] CF1 Rivoli x Sébastopol',
       '[Paris] CF318 Rivoli x Lobau',
       '[Paris] CF4 Poissonnière x Montmartre OUEST',
       '[Paris] CF892 Rivoli x Bourdonnais', '[Paris] Quai de Jemmapes',
       '[Paris] Quai de Valmy', '[Paris] Rivoli x Nicolas Flamel'],
      dtype='object')

In [62]:
df_to_plot.columns[0].split('_')[0]

'Hour'